### ISSUE TITLE
Traduccion de Comandos

### ISSUE THREAD

**Issue by DJ-Tijeras** [TheWleDey/Dropp#1]
Mira, estuve viendo tu repositorio y me parecio buena idea traducir la mayoria de los comandos, como  warn,mute,kick,customavatar,etc.

Nose si me entiendes, pero ami me parecio una muy buena Idea

**Comment by TheWleDey** [comment]
He pensado en eso, Pero la cosa esque no he tenido mucho tiempo para hacerlo, si quieres ayudarme pues depende de ti

**Comment by DJ-Tijeras** [comment]
Me gustaria ayudar, pero como tu tambien estoy ocupado, intentare hacerlo cuando pueda

**Comment by TheWleDey** [comment]
Lo siento tijeras, pero ya el git no lo uso
